// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_soPvbMj5zcqRKc6u7jphTHuJagfPBro',
    appId: '1:822114791422:web:3a192f1ba47c5395f31aaf',
    messagingSenderId: '822114791422',
    projectId: 'cpd-nestease-denzelbaldacchino',
    authDomain: 'cpd-nestease-denzelbaldacchino.firebaseapp.com',
    storageBucket: 'cpd-nestease-denzelbaldacchino.firebasestorage.app',
    measurementId: 'G-BMC9QVTBGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7gYPyxNGvMKOI25cRS5GJdWGF1N4U1Wo',
    appId: '1:822114791422:android:dfd9d0d32ea52680f31aaf',
    messagingSenderId: '822114791422',
    projectId: 'cpd-nestease-denzelbaldacchino',
    storageBucket: 'cpd-nestease-denzelbaldacchino.appspot.com',
    databaseURL:
        'https://cpd-nestease-denzelbaldacchino-default-rtdb.europe-west1.firebasedatabase.app', // UPDATED
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTZyeTABljmFbHch5I1jhi6YnsjaVUIxA',
    appId: '1:822114791422:ios:4ac5a8ed6886dc10f31aaf',
    messagingSenderId: '822114791422',
    projectId: 'cpd-nestease-denzelbaldacchino',
    storageBucket: 'cpd-nestease-denzelbaldacchino.firebasestorage.app',
    iosBundleId: 'com.example.homeManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTZyeTABljmFbHch5I1jhi6YnsjaVUIxA',
    appId: '1:822114791422:ios:4ac5a8ed6886dc10f31aaf',
    messagingSenderId: '822114791422',
    projectId: 'cpd-nestease-denzelbaldacchino',
    storageBucket: 'cpd-nestease-denzelbaldacchino.firebasestorage.app',
    iosBundleId: 'com.example.homeManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_soPvbMj5zcqRKc6u7jphTHuJagfPBro',
    appId: '1:822114791422:web:457d3a8d3c02fd4ff31aaf',
    messagingSenderId: '822114791422',
    projectId: 'cpd-nestease-denzelbaldacchino',
    authDomain: 'cpd-nestease-denzelbaldacchino.firebaseapp.com',
    storageBucket: 'cpd-nestease-denzelbaldacchino.firebasestorage.app',
    measurementId: 'G-GJ7FNQ8TF1',
  );
}
